version: 1.0.{build}
image: Visual Studio 2017
environment:
    my_encrypted_sonarqube_token:
        secure: 94Py9ytqrmqFVtmUiyayJJ4Hgg2vjF1+YuRJldGGWO82/9zEens+sCjeh7wzc2Le
install:
    - choco install "msbuild-sonarqube-runner" -y
before_build:
    - cmd: nuget restore Src/ReadMeSynchronizer.sln
    - MSBuild.SonarQube.Runner.exe begin /k:"TrevellickProject001" /d:"sonar.host.url=https://sonarqube.com" /d:sonar.login="$env:my_encrypted_sonarqube_token" /d:"sonar.organization=gregtrevellick-github" /v:"%APPVEYOR_BUILD_NUMBER%" /d:sonar.cs.opencover.reportsPaths="%CD%\coverage.xml"
build:
    project: Src/ReadMeSynchronizer.sln
    verbosity: minimal
after_build:
    - MSBuild.SonarQube.Runner.exe end /d:sonar.login="$env:my_encrypted_sonarqube_token"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true