version: 1.0.{build}
image: Visual Studio 2017
environment:
  SonarCloudGitHubAppVeyorTrevellickQwaszx1962600606byzqsgaibdtjxuilof:
    secure: LXz2lIEeX0qKZL6bGifEHA==
before_build:
- cmd: nuget restore Src/ReadMeSynchronizer.sln
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"Src/ReadMeSynchronizer.sln" /d:sonar.organization="gregtrevellick-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONAR_TOKEN%" /v:"%APPVEYOR_BUILD_NUMBER%" /d:sonar.cs.opencover.reportsPaths="%CD%\coverage.xml"
  - msbuild "Src/ReadMeSynchronizer.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SONAR_TOKEN%"
build:
  project: Src/ReadMeSynchronizer.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true