version: 1.0.{build}
image: Visual Studio 2017
environment:
  SonarCloudGitHubAppVeyorTrevellickQwaszx1962600606byzqsgaibdtjxuilof:
    secure: LXz2lIEeX0qKZL6bGifEHA==
install:
  - choco install "msbuild-sonarqube-runner" -y
before_build:
    - cmd: nuget restore Src/ReadMeSynchronizer.sln
    #Start SonarQube runner
    - MSBuild.SonarQube.Runner.exe begin /k:"Src/ReadMeSynchronizer.sln" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%SONAR_TOKEN%" /d:"sonar.organization=gregtrevellick-github" /v:"%APPVEYOR_BUILD_NUMBER%" /d:sonar.cs.opencover.reportsPaths="%CD%\coverage.xml"
build:
  project: Src/ReadMeSynchronizer.sln
  verbosity: minimal
after_build:
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SONAR_TOKEN%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
