version: 1.0.{build}
image: Visual Studio 2017
environment:
    my_encrypted_sonarqube_token:
        secure: 94Py9ytqrmqFVtmUiyayJJ4Hgg2vjF1+YuRJldGGWO82/9zEens+sCjeh7wzc2Le
install:
    - choco install "sonarscanner-msbuild-net46" -y
    - cmd: SET NODE_PATH=%AppData%\npm\node_modules 
    - cmd: npm install -g typescript
    # Output useful info for debugging.
    - cmd: node --version
    - cmd: yarn --version
before_build:
    - cmd: nuget restore ReadMeSynchronizer.sln
    - SonarScanner.MSBuild.exe begin /k:"ReadMeSynchronizer" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%my_encrypted_sonarqube_token%" /d:"sonar.organization=gregtrevellick-github"
build:
    project: ReadMeSynchronizer.sln
    verbosity: minimal
after_build:
    - SonarScanner.MSBuild.exe end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true